Feature/dwc-a interface for publication
zebbra/data_aggregator pull request #227
Opened 2024-03-27 13:31 UTC by cloedu87

- [x] needs re-init of the database on staging due to fundamental conceptal changes of the datamodel (requested by customer)
- [x] export of records in csv files
- [x] each dwc extension has its own file
- [x] all csv files get bundled to a dwc-a file which is basically a regular zip file
- [x] publication runs in a async job
- [x] state handling for publication jobs
- [x] `fast_track_status` and `approval_status` for the record to track publication progress of single records
- [ ] job to periodically test if records in fast_track_status `in_publication` are now present on the hosted portal, then trasition to state `published`
- [ ] job to periodically test if records in approval_status `in_publication` are now present on gbif.org, then trasition to state `published`
- [x] move approval_status and fast_track_status to `stale` (have to be republished) if a new import or encoding changes data
- [x] frontend: button to trigger approval-publication
- [x] frontend: button to trigger fast-track-publication
- [x] frontend: overview for past publications and their artifacts
- [x] frontend: state change history for past publications (over paper_trail versioning)
- [x] frontend: error handling for uploaded files
- [x] MIDS data quality rating BE and FE
- [x] enrichment of collections with GrSciColl data on creation (ash change)
- [x] refactoring and dedup code within export and publication modules
- [x] add paper_trail for encoded_record resource to extend the Change history with encoded_record changes

2024-04-25 14:05 UTC, hwuethrich requested changes
@cloedu87 First batch of review 😅

2024-04-25 14:05 UTC, hwuethrich commented on lib/data_aggregator/records/grscicoll/lookup.ex
Maybe extract in separate module `Gbif.GRSciColl` for reusability?

2024-04-25 14:05 UTC, hwuethrich commented on lib/data_aggregator/records/publication/publication.ex
> +    attribute :records_query, :term, allow_nil?: false
This will probably dump the query struct as binary (and will fail, if the `Ash.Query` is updated). Maybe just store the filter as params?

2024-04-25 14:05 UTC, hwuethrich commented on lib/data_aggregator/records/record/record.ex
> +
Maybe this could be simplified? Also, level 4 is `or`ed (instead of `and`ed?) Maybe a normalized score (0.0 - 1.0) would be better than levels? There is `num_nulls` and `num_notnull` in Postgres (https://www.postgresql.org/docs/current/functions-comparison.html#FUNCTIONS-COMPARISON-FUNC-TABLE)

2024-04-25 14:05 UTC, hwuethrich commented on lib/data_aggregator/records/types/data_layer_type.ex
> +  defstruct []
Is this used? Also in other types...

2024-05-06 07:41 UTC, cloedu87 commented on lib/data_aggregator/records/publication/publication.ex
> +    attribute :records_query, :term, allow_nil?: false
done, as well as for the export Resource

2024-05-06 07:41 UTC, cloedu87 commented on lib/data_aggregator/records/grscicoll/lookup.ex
done, moved to `Gbif.GRSciColl` Module out of resources

2024-05-06 07:42 UTC, cloedu87 commented on lib/data_aggregator/records/record/record.ex
> +
as discussed already, the functionality is correct ( and/or ) but I'm working on it to extract it to separate modules instead of having all the expressions in the Resource

2024-05-06 07:54 UTC, cloedu87 commented on lib/data_aggregator/records/types/data_layer_type.ex
> +  defstruct []
it is normaly used to have a working type definition (on the next line) for usage in  `spec()`

but you're right, on some places it's not necessary, so I removed them

2024-05-06 14:13 UTC, cloedu87 commented on lib/data_aggregator/records/record/record.ex
> +
its now done as well under the modules `Mids.LevelOne`,  `Mids.LevelTwo`,  `Mids.LevelThree`,  `Mids.LevelFour`

2024-05-07 13:17 UTC, hwuethrich approved these changes
Looks good! 🎉 But have a look at my minor suggestions before merging.

2024-05-07 13:17 UTC, hwuethrich commented on lib/data_aggregator/records/record/actions/encode_record.ex
>          set_failed_state(record)
Maybe pattern match on expected return value?

2024-05-07 13:17 UTC, hwuethrich commented on lib/data_aggregator/records/record/actions/encode_record.ex
> +        {:error, error}
Using `with` instead of `case` allows you to omit the error clause

2024-05-07 13:17 UTC, hwuethrich commented on lib/data_aggregator/records/record/actions/encode_record.ex
>    end
Use ! for function that could raise exceptions

2024-05-07 13:17 UTC, hwuethrich commented on lib/data_aggregator/records/record/actions/export_records.ex
> +    file_path = "#{directory}/#{Ecto.UUID.generate()}.csv"
Consider using UUIDv7, which use the timestamp as prefix (and can be chronologically ordered, maybe useful for cleanup job):

```elixir
iex(6)> Uniq.UUID.uuid7(:slug)
"AY9TGKnMcOim8xEooBT_ww"
iex(7)> Uniq.UUID.uuid7(:slug)
"AY9TGK7ud7WUi9EMr1QkRA"
```

2024-05-07 13:17 UTC, hwuethrich commented on lib/data_aggregator/records/record/actions/publish.ex
> +  end
Is the !-suffix required? How can this fail? Maybe just return `update_status` return value?

Not sure if you are within a DB transaction and assuming `Publication.add_publication_progress(publication, 1)` will increment a column, but if you are: just be aware that the updated progress value will only be visible to other processes after the transaction is commited.

2024-05-07 13:17 UTC, hwuethrich commented on lib/data_aggregator/records/record/record.ex
> +
Not sure about performance (make sure relevant fields are indexed). Could possibly also be calculated on INSERT/UPDATE using https://www.postgresql.org/docs/current/ddl-generated-columns.html

2024-05-07 14:19 UTC, cloedu87 commented on lib/data_aggregator/records/record/record.ex
> +
yes I created an [issue](https://github.com/zebbra/data_aggregator/issues/266) to follow up on this, didn't had time to dive deep in the topic yet

2024-05-07 14:19 UTC, cloedu87 commented on lib/data_aggregator/records/record/actions/publish.ex
> +  end
1. I slightly chached the logic, so it may raise if Publicatin.add_publication_progress(...) raises

2. yes, thats true. we have this problem at multiple places (export, publication, encoding...) and we have to solve this, but for now it's fine, because generally jobs only take several seconds up to 1 minute and for the user this should be fine for now. at least at the end of the action/job we have the reported numbers of affected items.

2024-05-07 14:19 UTC, cloedu87 commented on lib/data_aggregator/records/record/actions/export_records.ex
> +    file_path = "#{directory}/#{Ecto.UUID.generate()}.csv"
generally refactored it to use `Uniq.UUID.uuid7(:slug)` instead

2024-05-07 14:19 UTC, cloedu87 commented on lib/data_aggregator/records/record/actions/encode_record.ex
>    end
done

2024-05-07 14:19 UTC, cloedu87 commented on lib/data_aggregator/records/record/actions/encode_record.ex
> +        {:error, error}
done

2024-05-07 14:19 UTC, cloedu87 commented on lib/data_aggregator/records/record/actions/encode_record.ex
>          set_failed_state(record)
I changed it to `set_failed_state!(...)` because if this trivial operation (ash resource update) fails it should raise

2024-05-07 15:16 UTC, merged