WIP refactor(subscriptions): simple version done
zebbra/data_aggregator pull request #307
Opened 2024-06-13 15:00 UTC by mbaertschi

## Done
- [x]  Attribute selection for mapping is too small (https://infofauna-support.atlassian.net/browse/SCN-233)
- [x]  Do not show add import button if no entries are found due to filtering (https://infofauna-support.atlassian.net/browse/SCN-237)
- [x] Re-order and rename layers (https://infofauna-support.atlassian.net/browse/SCN-213)
- [x] Re-name and re-color actions in modals / alerts (https://infofauna-support.atlassian.net/browse/SCN-214)
- [x] Hide GrSciColl on collection edit (https://infofauna-support.atlassian.net/browse/SCN-212)
- [x] Do not show create import if export / publications are empty (https://infofauna-support.atlassian.net/browse/SCN-221)
- [x] Remove Tasks from navbar (https://infofauna-support.atlassian.net/browse/SCN-240)
- [x] Make all collection level actions atomic via state_machine on collection (https://infofauna-support.atlassian.net/browse/SCN-239)

## TODO
- [x] use state_machine on collection for action_state -> importing, exporting, encoding, fast_tracking, approving, idle
- [x] before each action, validate that action_state is in state idle (enforce with state_machine transitions)
- [x] expose apis for actions only over the collection api (so that graphql and rest api also need to go over the state_machine)
- [x] remove added aggregations and calculations and replace them with the state_machine state

2024-06-14 15:18 UTC, cloedu87 requested changes

2024-06-14 15:18 UTC, cloedu87 commented on lib/data_aggregator/gbif/rest_api.ex
> +    exclude_collections_in_use(body["results"])
this behavior is maybe not expected if one calls `lookup_all_collections`. it might be better to have another function `lookup_collection_not_already_in_use` or similar, to have a clear api of this module

2024-06-14 15:18 UTC, cloedu87 commented on lib/data_aggregator/records/collection/changes/set_encoding.ex
> +    if collection.records_count_encoding == 0 do
this will be `false` as soon as something was encoded, but IMHO this isn't a condition to set the status of the collection back to `:idle`.

Suggestion:
better would be to call `Collection.encoding_state` to verify if no record of the collection is still in `:encoding`

2024-06-14 15:18 UTC, cloedu87 commented on lib/data_aggregator_web/live/collection_live/export/modal.ex
> +         |> assign_and_redirect(export)}
here you don't assign the updated record from the return tuple `{:ok, _}`. if desired, it would make sense to have the "queued" and therefore most recent export object assigned like...

```
{:ok, export} ->
        ...
         |> assign_and_redirect(export)}
```

2024-06-14 15:18 UTC, cloedu87 commented on lib/data_aggregator_web/live/collection_live/publication/subscriptions.ex
> +
this is black magic to me, but I trust you ;-)

2024-06-15 08:05 UTC, mbaertschi commented on lib/data_aggregator/records/collection/changes/set_encoding.ex
> +    if collection.records_count_encoding == 0 do
collection.records_count_encoding is an aggregated count on collection > records > state == `encoding`. so this does exactly what you supposed it should do :-)

2024-06-16 08:21 UTC, mbaertschi commented on lib/data_aggregator_web/live/collection_live/publication/subscriptions.ex
> +
it's basically:

1. subscribe to topics you want to be notified about
2. by using `use xxx.subscriptions` you automatically implement the `handle_info` callback for ash notifications. the callback itself calls the handle_notifications function where you define the actions you want to apply for the topic and event you receive

2024-06-17 11:34 UTC, cloedu87 approved these changes

2024-06-17 12:47 UTC, merged