Feature/publication
zebbra/data_aggregator pull request #53
Opened 2023-11-23 10:35 UTC by cloedu87

New Resources and Actions to publish records to a csv files on s3 with or without a custom mapping

- [x] on a `Collection` there is a action to `CollectReviewableRecords` according to the configured `:reviewer` on the collection. As soon as we have the specification on how to collect records for each reviewer, we can implement there a function to filter records according to their needs
- [x] `Export` is the representation of the exported records holding a reference to the exported file and the mapping with which it was created. the Action `publish` creates the file from the records and the mapping on the export and ships it to s3
- [x] statemachine for export
- [x] oban integration to have exports in async jobs
- [x] `runner_test.exs` and `export_test.exs` the test for the new resources

2023-12-12 15:26 UTC, hwuethrich requested changes
As discussed :)

2023-12-12 15:26 UTC, hwuethrich commented on lib/data_aggregator/platform/publication/actions/publish.ex
> +    export = DataAggregator.Platform.load!(input.arguments.export, [:records])
This is probably a problem, if there are a lot of records. Maybe you could stream the results? https://hexdocs.pm/ash/Ash.Api.html#c:stream!/2

2023-12-12 15:26 UTC, hwuethrich commented on lib/data_aggregator/platform/publication/changes/enque_runner.ex
Typo in file name 🤓

2023-12-13 16:23 UTC, cloedu87 commented on lib/data_aggregator/platform/publication/actions/publish.ex
> +    export = DataAggregator.Platform.load!(input.arguments.export, [:records])
done

2023-12-13 16:27 UTC, cloedu87 commented on lib/data_aggregator/platform/publication/changes/enque_runner.ex
done

2024-01-10 15:07 UTC, hwuethrich commented on lib/data_aggregator/records/record/actions/export_records.ex
> +    Export.update_attachment(export, attachment)
Maybe add some error handling?

```elixir
with {:ok, export} <- Export.update(export, %{exported_count: Records.count!(records_query)}),
    {:ok, export} <- Export.update_mapping(export, mapping),
    {:ok, export} <- Export.update_attachment(export, attachment) do
  {:ok, export}
end
```

or

```elixir
export
|> Export.update!(%{exported_count: Records.count!(records_query)})
|> Export.update_mapping!(mapping)
|> Export.update_attachment!(attachment)
```

2024-01-10 17:20 UTC, cloedu87 commented on lib/data_aggregator/records/record/actions/export_records.ex
> +    Export.update_attachment(export, attachment)
thx and check 🙋🏽‍♂️

2024-02-13 18:14 UTC, cloedu87 commented
it fails because a migration is not committed, but this will be obsolet due to the migrations of the [encoding-pr](https://github.com/zebbra/data_aggregator/pull/92)

2024-03-11 19:20 UTC, mbaertschi approved these changes
Are the headers correctly aligned?

2024-03-11 19:23 UTC, hwuethrich approved these changes

2024-03-11 19:24 UTC, mbaertschi approved these changes

2024-03-11 19:57 UTC, merged